USE AUTOELECT;
DROP TABLE IF EXISTS  ADULT_CANDIDATES;
DROP TABLE IF EXISTS  ELENGOMATS;
DROP TABLE IF EXISTS  TEMPUSERS;
DROP TABLE IF EXISTS  TROOPS;
DROP TABLE IF EXISTS  USERS;
DROP TABLE IF EXISTS  YOUTH_CANDIDATES;

 CREATE TABLE `ADULT_CANDIDATES` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(255) DEFAULT NULL,
  `TROOP_NUM` int(11) DEFAULT NULL,
  `DATE_ELECTED` date DEFAULT NULL,
  `BIRTHDATE` date DEFAULT NULL,
  `ADDERESS` varchar(255) DEFAULT NULL,
  `EMAIL` varchar(255) DEFAULT NULL,
  `PHONE` varchar(255) DEFAULT NULL,
  `ORDEAL_DATE` date DEFAULT NULL,
  PRIMARY KEY (`ID`)
);

CREATE TABLE `ELENGOMATS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(255) DEFAULT NULL,
  `USERNAME` varchar(255) DEFAULT NULL,
  `EMAIL` varchar(255) DEFAULT NULL,
  `ADDRESS` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
); 

 CREATE TABLE `TEMPUSERS` (
  `EMAIL` varchar(100) DEFAULT NULL,
  `NAME` varchar(50) DEFAULT NULL,
  `ID` varchar(100) DEFAULT NULL,
  `TYPE` int(1) DEFAULT NULL
);

CREATE TABLE `TROOPS` (
  `NUMBER` int(11) NOT NULL DEFAULT '0',
  `ADDRESS` varchar(255) DEFAULT NULL,
  `COMMENT` varchar(2048) DEFAULT NULL,
  `SCOUTMASTER_NAME` varchar(255) DEFAULT NULL,
  `SCOUTMASTER_EMAIL` varchar(255) DEFAULT NULL,
  `COMMITTEE_NAME` varchar(255) DEFAULT NULL,
  `COMMITTEE_EMAIL` varchar(255) DEFAULT NULL,
  `PRIMARY_ELENGOMAT` int(11) DEFAULT NULL,
  `SECONDARY_ELENGOMAT` int(255) DEFAULT NULL,
  `DISTRICT` varchar(255) DEFAULT NULL,
  `ELECTION_DATE` date DEFAULT NULL,
  `MEMBERS` int(11) DEFAULT NULL,
  PRIMARY KEY (`NUMBER`)
);

CREATE TABLE `USERS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `USERNAME` varchar(50) DEFAULT NULL,
  `PASSWORD` varchar(50) DEFAULT NULL,
  `HASH` varchar(500) DEFAULT NULL,
  `SALT` varchar(500) DEFAULT NULL,
  `PERMISSION` int(11) DEFAULT NULL,
  `NAME` varchar(100) DEFAULT NULL,
  `EMAIL` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`ID`)
);

 CREATE TABLE `YOUTH_CANDIDATES` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(255) DEFAULT NULL,
  `TROOP_NUM` int(11) DEFAULT NULL,
  `DATE_ELECTED` date DEFAULT NULL,
  `BIRTHDATE` date DEFAULT NULL,
  `ADDERESS` varchar(255) DEFAULT NULL,
  `EMAIL` varchar(255) DEFAULT NULL,
  `PARENT_EMAIL` varchar(255) DEFAULT NULL,
  `PHONE` varchar(255) DEFAULT NULL,
  `ORDEAL_DATE` date DEFAULT NULL,
  PRIMARY KEY (`ID`)
);

CREATE TABLE PENDING_EMAILS (
`ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
DATE DATE null,
NAME VARCHAR(255) ,
ADDRESS VARCHAR(255) ,
SUBJECT VARCHAR(255) ,
BODY TEXT ,
TOKEN VARCHAR(255) ,
IS_REMINDER bool 
);

INSERT INTO USERS (EMAIL, NAME, PERMISSION, USERNAME, HASH) VALUES
      ('sb205@zips.uakron.edu','admin',1,'admin','$2y$10$hiJwQlvct/vXozqCNu2kje8RBprsfRe7iIWP4KH0cd9AGUgsSArVq');

